#!/usr/bin/env bash
#
# przm platform bootstrap. Run once on a fresh box (or after wiping config).
#
# Generates the EdDSA signing keypair, mints random operator secrets, prompts
# for the few things only you know (domain + Neon URLs), and writes:
#   .env          — compose env (env-file)
#   cortex.yaml   — cortex memory config with RLS + tenant role
#   Caddyfile     — Caddy reverse-proxy config (auto-TLS for both domains)
#
# Host prereqs: docker, jq, openssl. (The keygen runs in a one-shot node:20
# container so you don't need Node on the host.)
#
# Re-running the script with an existing .env will refuse to overwrite. Delete
# `.env` (and your DNS / DB if you're starting clean) to re-run.

set -euo pipefail

cd "$(dirname "$0")"

need() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "bootstrap: '$1' is required on the host" >&2
    exit 1
  }
}
need docker
need jq
need openssl
need sed

if [[ -f .env ]]; then
  echo "bootstrap: .env already exists. Refusing to overwrite." >&2
  echo "  Delete .env to re-run (this rotates the EdDSA keypair + secrets)." >&2
  exit 1
fi

prompt() {
  local var="$1" label="$2" default="${3-}"
  local val
  if [[ -n "$default" ]]; then
    read -r -p "$label [$default]: " val
    val="${val:-$default}"
  else
    read -r -p "$label: " val
  fi
  printf -v "$var" '%s' "$val"
}

echo
echo "== przm platform bootstrap =="
echo
prompt DOMAIN_BASE "Platform domain base (e.g. example.com)"
prompt ACCESS_DATABASE_URL "Access service Postgres URL (Neon)"
prompt CORTEX_DATABASE_URL "Cortex memory Postgres URL (Neon)"
prompt CORTEX_DB_APP_ROLE "Cortex restricted DB role (NOSUPERUSER)" "cortex_app"
prompt ACCESS_DB_APP_ROLE_RAW "Access restricted DB role (blank to skip)" ""
prompt OPENROUTER_API_KEY "OpenRouter API key (blank to skip)" ""

CORTEX_DOMAIN="cortex.$DOMAIN_BASE"
ACCESS_DOMAIN="access.$DOMAIN_BASE"
ACCESS_ISSUER="https://$ACCESS_DOMAIN"
ACCESS_AUDIENCE="przm-platform"

echo
echo "Generating EdDSA keypair (jose in a one-shot node:20 container)..."

keygen_out=$(docker run --rm --pull=missing -i node:20-alpine sh -c '
  set -e
  cd /tmp
  npm init -y >/dev/null 2>&1
  npm install --silent --no-fund --no-audit jose >/dev/null 2>&1
  node -e "
    import(\"jose\").then(async (j) => {
      const { publicKey, privateKey } = await j.generateKeyPair(\"EdDSA\", { extractable: true });
      process.stdout.write(JSON.stringify({
        priv: await j.exportJWK(privateKey),
        pub: await j.exportJWK(publicKey)
      }));
    }).catch(e => { console.error(e); process.exit(1); });
  "
')

ACCESS_PRIVATE_JWK=$(jq -c .priv <<<"$keygen_out")
ACCESS_PUBLIC_JWK=$(jq -c .pub <<<"$keygen_out")

ACCESS_ADMIN_API_KEY="adm_$(openssl rand -hex 24)"
CORTEX_MCP_AUTH_TOKEN=$(openssl rand -hex 32)

echo "Writing .env, cortex.yaml, Caddyfile..."

# Caddyfile.
sed \
  -e "s|__CORTEX_DOMAIN__|${CORTEX_DOMAIN}|g" \
  -e "s|__ACCESS_DOMAIN__|${ACCESS_DOMAIN}|g" \
  Caddyfile.template > Caddyfile

# cortex.yaml — quote the DSN to survive YAML's special chars.
cortex_dsn_escaped=${CORTEX_DATABASE_URL//\"/\\\"}
sed \
  -e "s|__CORTEX_DATABASE_URL__|\"${cortex_dsn_escaped}\"|g" \
  -e "s|__CORTEX_DB_APP_ROLE__|${CORTEX_DB_APP_ROLE}|g" \
  cortex.yaml.template > cortex.yaml

# .env. Heredoc rather than sed so the JWK JSON commas + quotes survive cleanly.
umask 077
cat > .env <<ENV
# Generated by ./bootstrap.sh — do not commit. Rotate by deleting + re-running.
CORTEX_DOMAIN=${CORTEX_DOMAIN}
ACCESS_DOMAIN=${ACCESS_DOMAIN}
ACCESS_ISSUER=${ACCESS_ISSUER}
ACCESS_AUDIENCE=${ACCESS_AUDIENCE}
ACCESS_IMAGE_TAG=latest
CORTEX_IMAGE_TAG=latest
ACCESS_DATABASE_URL=${ACCESS_DATABASE_URL}
CORTEX_DATABASE_URL=${CORTEX_DATABASE_URL}
CORTEX_DB_APP_ROLE=${CORTEX_DB_APP_ROLE}
ACCESS_DB_APP_ROLE=${ACCESS_DB_APP_ROLE_RAW}
ACCESS_PRIVATE_JWK=${ACCESS_PRIVATE_JWK}
ACCESS_PUBLIC_JWK=${ACCESS_PUBLIC_JWK}
ACCESS_JWT_TTL_SECONDS=3600
ACCESS_ADMIN_API_KEY=${ACCESS_ADMIN_API_KEY}
CORTEX_MCP_AUTH_TOKEN=${CORTEX_MCP_AUTH_TOKEN}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
WORKOS_API_KEY=
WORKOS_CLIENT_ID=
WORKOS_REDIRECT_URI=
ENV
chmod 600 .env

cat <<EOF

== Done. Next steps ==

1. DNS — point A/AAAA records at this server for:
     ${CORTEX_DOMAIN}
     ${ACCESS_DOMAIN}
   (Caddy fetches Let's Encrypt certs automatically on first request.)

2. Postgres roles — run the SQL in README.md §"Role setup" against your Neon
   project to create the restricted role and grant table privileges.

3. Bring the stack up:
     docker compose -f docker-compose.platform.yml --env-file .env pull
     docker compose -f docker-compose.platform.yml --env-file .env up -d

4. Verify:
     docker compose -f docker-compose.platform.yml ps
     curl https://${ACCESS_DOMAIN}/health
     curl -H "Authorization: Bearer \$CORTEX_MCP_AUTH_TOKEN" \\
          https://${CORTEX_DOMAIN}/api/health

5. Create your first tenant — see README.md §"First tenant" for the admin-API
   calls (ACCESS_ADMIN_API_KEY in .env gates them).

Operator secrets are in .env (chmod 600). Keep that file off-system backups.
EOF
