#!/usr/bin/env node
/**
 * Cross-platform git hook installer.
 *
 * Writes `.git/hooks/pre-commit` so it shells out to
 * `scripts/pre-commit-scan.sh` on commit. Works the same from
 *   - macOS / Linux (bash)
 *   - Windows PowerShell
 *   - Windows cmd
 *   - Git Bash
 *
 * because Node is the only binary this script needs — and any Cortex
 * contributor already has Node installed for the workspace.
 *
 * Git itself runs the pre-commit hook through the bash it ships with
 * (Git for Windows includes bash), so the hook file continues to use
 * the `#!/usr/bin/env bash` shebang internally.
 *
 * Run from the repo root:
 *     node scripts/install-hooks.mjs
 */
import { writeFileSync, chmodSync } from "node:fs";
import { execSync } from "node:child_process";
import path from "node:path";

function resolveRepoRoot() {
  try {
    return execSync("git rev-parse --show-toplevel", { encoding: "utf8" }).trim();
  } catch (err) {
    process.stderr.write(
      `install-hooks: could not locate git root (${err instanceof Error ? err.message : String(err)}).\n`,
    );
    process.exit(1);
  }
}

const repoRoot = resolveRepoRoot();
const hooksDir = path.join(repoRoot, ".git", "hooks");
const scanScript = path.join(repoRoot, "scripts", "pre-commit-scan.sh");

const hookBody = `#!/usr/bin/env bash\n# Auto-generated by scripts/install-hooks.mjs.\n# Do not edit — re-run the installer to refresh.\nexec "${scanScript.replace(/\\/g, "/")}" "$@"\n`;

const hookPath = path.join(hooksDir, "pre-commit");
writeFileSync(hookPath, hookBody, "utf8");
try {
  chmodSync(hookPath, 0o755);
} catch {
  // chmod is a no-op on some Windows filesystems; git runs the hook
  // through bash which doesn't need the +x bit on Windows.
}

process.stdout.write(`installed: ${hookPath} -> ${scanScript}\n`);
process.stdout.write("done.\n");
